name: OWASP ZAP Scan

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "azikkw"
          password: "150203azikkw"
        
      - name: Set up OWASP ZAP
        uses: zaproxy/action-full-scan@v0.1.0
        with:
          target: "https://cloud-app-dev-amen.uc.r.appspot.com/"
          docker_name: "owasp/zap2docker-stable"
          cmd_options: "-r zap_report.html"

      - name: Upload OWASP ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html
